export const SET_INVESTMENTS = 'GET_INVESTMENTS'
export const SET_REWARDS = 'GET_REWARDS'

export const GET_CAPITAL_POOL_APR = 'GET_CAPITAL_POOL_APR'
export const GET_LIQUIDITY_POOL_APR = 'GET_LIQUIDITY_POOL_APR'

export const SET_BALANCE = 'BALANCE'

export const SET_STAKE = 'STAKE'

export const CLAIM_REWARDS = 'CLAIM_REWARDS'
