export const MASTER_CONTRACT_ADDRESS = process.env.REACT_APP_MASTER_CONTRACT_ADDRESS
export const VAULT_CONTRACT_ADDRESS = process.env.REACT_APP_VAULT_CONTRACT_ADDRESS
export const SOLACE_CONTRACT_ADDRESS = process.env.REACT_APP_SOLACE_CONTRACT_ADDRESS
export const ERC20FARM_CONTRACT_ADDRESS = process.env.REACT_APP_ERC20FARM_CONTRACT_ADDRESS

export const NUM_BLOCKS_PER_DAY = 6500
export const NUM_DAYS_PER_MONTH = 30
export const DAYS_PER_YEAR = 365
