export enum AnalyticsChart {
  PREMIUMS_STAT = '0',
  UWP_SIZE_STAT = '1',
  LEVERAGE_FACTOR_STAT = '2',
  TOKEN_COMPOSITION_TABLE = '3',
  PORTFOLIO_AREA_CHART = '4',
  PORTFOLIO_VOL_HISTOGRAM = '5',
  TOKEN_PRICE_VOL_HISTOGRAM = '6',
  TOKEN_RADIAL_PIE_CHART = '7',
  TOKEN_WEIGHTS_AREA_CHART = '8',
  PREMIUMS_LINE_CHART = '9',
  SPI_EXPOSURES_TABLE_APPID = '10',
}
